apiVersion: v1
kind: Secret
metadata:
  name: sentinel-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: sentinel
  GMAIL_APP_PASSWORD: "khtt xuhn wfgv mhis"
  JWT_SECRET_KEY: "dev-most-secret-key"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
data:
  POSTGRES_USER: sentinel
  POSTGRES_DB: sentinel
  POSTGRES_HOST: postgres
  REDIS_HOST: redis
  GMAIL_ADDRESS: suat92645@gmail.com
  ALERT_TO_EMAIL: suatdurkaya07@gmail.com
