apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
data:
  POSTGRES_USER: sentinel
  POSTGRES_DB: sentinel
  POSTGRES_HOST: postgres
  REDIS_HOST: redis
  GMAIL_ADDRESS: suat92645@gmail.com
